server:
  port: 8123

spring:
  cloud:
    gateway:
      routes:
        - id: myGateway
          uri: http://localhost:8083
          predicates:
            - Path=/api-gateway/**
          filters:
            - StripPrefix=1
            - PrefixPath=/gateway
            - MyPre
            - MyPost
            - MyKeyValue=hello, world
            - name: MyArgs
              args:
                name: tom
                age: 18
                address: china


        - id: mySystem
          uri: http://localhost:8083
          predicates:
            - Path=/api-system/**
          filters:
            - StripPrefix=1
            - PrefixPath=/system

        - id: myCustomer
          uri: http://localhost:8083
          predicates:
            - Path=/api-customer/**
          filters:
            - StripPrefix=1
            - PrefixPath=/customer
