server:
  port: 8123

spring:
  cloud:
    gateway:
      routes:
        - id: myGateway
          uri: http://localhost:8083
          predicates:
            - Path=/api-gateway/**
          filters:
            - StripPrefix=1
            - PrefixPath=/gateway

        - id: mySystem
          uri: http://localhost:8083
          predicates:
            - Path=/api-system/**
          filters:
            - StripPrefix=1
            - PrefixPath=/system

        - id: myCustomer
          uri: http://localhost:8083
          predicates:
            - Path=/api-customer/**
          filters:
            - StripPrefix=1
            - PrefixPath=/customer
