server:
  port: 8123

spring:
  cloud:
    gateway:
      routes:
        - id: crm_gateway
          uri: http://localhost:7011
          predicates:
            - Path=/crm-zuul/**
          filters:
            - StripPrefix=1
            - Post
        - id: crm_system
          uri: http://localhost:7011
          predicates:
            - Path=/crm-admin/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api-user
        - id: crm_custom
          uri: http://localhost:7011
          predicates:
            - Path=/crm-custom/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api-custom
