server:
  port: 8123

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://peer1:8001/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          # 默认使用大写的 service-id, 这个选项允许改成小写
          lower-case-service-id: true
      routes:
        - id: myGateway
          uri: http://localhost:8083
          predicates:
            - Path=/api-gateway/**
          filters:
            - StripPrefix=1
            - PrefixPath=/gateway
            - MyArgs=Tom,18,china GuangDong ShenZhen
            - MyPre
            - MyPost
            - MyKeyValue=hello, world

        - id: mySystem
          uri: http://localhost:8083
          predicates:
            - Path=/api-system/**
          filters:
            - StripPrefix=1
            - PrefixPath=/system

        - id: myCustomer
          uri: http://localhost:8083
          predicates:
            - Path=/api-customer/**
          filters:
            - StripPrefix=1
            - PrefixPath=/customer

        - id: msUser
          uri: lb://simple-user
          predicates:
            - Path=/ms-user/**
          filters:
            - RewritePath=/ms-user/(?<remaining>.*), /$\{remaining}
